version: "3"
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    image: eclipse-mosquitto:latest
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      # - ./ca.crt:/etc/mosquitto/ca_certificates/ca.crt
      # - ./server.crt:/etc/mosquitto/certs/server.crt
      # - ./server.key:/etc/mosquitto/certs/server.key
    ports:
      - "1883:1883"
    networks:
      - net

  influxdb:
    container_name: influxdb
    restart: always
    image: arm32v7/influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb/data
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUX_USER}
      - INFLUXDB_ADMIN_PASSWPRD=${INFLUX_PASS}
    networks:
      - net

  receiver:
    container_name: receiver
    restart: always
    depends_on:
      - influxdb
    image: receiver
    links:
      - influxdb
    environment:
      - INFLUX_TOKEN=${INFLUX_TOKEN}
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_URL=${INFLUX_URL}
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_USER=${INFLUX_USER}
      - INFLUX_PASS=${INFLUX_PASS}
    volumes:
      - ./ca.crt:/app/ca.crt
    networks:
      - net

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    networks:
      - net

volumes:
  influxdb-storage:
  grafana-data:

networks:
  net:
    driver: bridge
